# Generated by Django 5.1.5 on 2025-02-02 07:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("news", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="post",
            name="post",
            field=models.TextField(default=1),
            preserve_default=False,
        ),
    ]
