# Generated by Django 5.1.5 on 2025-03-02 05:59

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("news", "0002_post_post"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="category",
            name="subscribers",
            field=models.ManyToManyField(
                blank=True,
                null=True,
                related_name="categories",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
